# %Clustering Node Parameter
min_pts: 10.0
min_eps: 0.3
window_boundary: 3

# %Tracking Node Parameter
dist_threshold: 1.4
min_range: 0.5
wait_time: 4.0

# --State Transition Matrix (4x4)
A: [1,    0,    0.1,  0,
    0,    1,    0,    0.1,
    0,    0,    1,    0,
    0,    0,    0,    1]

# --Observation Marix (4x4)
C: [1,    0,    0,    0,
    0,    1,    0,    0,
    0,    0,    1,    0,
    0,    0,    0,    1]

# --Measurment Error Covariance Matrix (4x4)
R: [0.5,  0,    0,    0,
    0,    0.5,  0,    0,
    0,    0,    0.5,  0,
    0,    0,    0,    0.5]

# --State Convariance Matrix (4x4)
P: [5,    0,     5,    0,
    0,     5,    0,     5,
    5,    0,     5,    0,
    0,     5,    0,     5]

# --Process Noise Matrix value of Q --> sigma_a
sigma_a : 30

# %Avoiding Node Parameter
# -- Kp_rel: Repulsive Gain, min_dist: minimum distance to detact object
Kp_rel: 0.015
Kp_att : 0.001
min_dist: 1.6
u_k: 0.03

# --Hardware System for Accompany System
# true -->Using Advanced Accompany System false -->Using Accompany System
isadvanced: false
wheel_radius: 0.1
wheel_interval: 0.46
base_range: 0.45
weight: 15

# --PID Gain Tuning
max_err_x: 6
max_err_y: 6
kp_x: 1.0
kp_y: 0.8
ki_x: 0.0
ki_y: 0.0
